# Confuguration for the battery model
battery_model:
  cell_capacity: 5 # [Ah]
  number_of_cells: 4

  # Coefficients for the equation https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9691840 (21)
  # k = C_eff / C = d0 + d1 * P_cell + d2 * P_cell^{2} + d3 * P_cell^{3}
  d0: 0.99876
  d1: -0.0020
  d2: -5.2484e-05
  d3: 1.2230e-07

  # Coefficients for the equation https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9691840 (18) 
best_speed_model:
  c0: 0.041546
  c1: 0.041122
  c2: 0.00053292

drone_mass: 0.9 # [kg]
drone_area: 0.0215 # [m^2]
average_acceleration: 10 # [m/s^2] Not tested at all, just a random value
propeller_radius: 0.119 # m
number_of_propellers: 4

